nmake clean
cls
Nmake /f Makefile.vc mode=dll WITH_DEVEL=%ROOT_DIR%%OPENSSL_DIR%\x86Debug WITH_SSL=dll WITH_ZLIB=dll ENABLE_WINSSL=no VC=%MsVCVersionNum% DEBUG=yes MAKE="NMAKE /e" ZLIB_LFLAGS=/libpath:%ROOT_DIR%%ZLIB_DIR%\DEBUG ZLIB_CFLAGS="/DHAVE_ZLIB_H /DHAVE_ZLIB /DHAVE_LIBZ /I%ROOT_DIR%%ZLIB_DIR%" ZLIB_LIBS=%ZLIB_IMPLIB%D.lib SSL_LIBS="%SSLLibD_space%" BASE_NAME=%LIBCURL_NAME% BASE_NAME_DEBUG=%LIBCURL_NAME%d

nmake /f Makefile.vc mode=dll WITH_DEVEL=%ROOT_DIR%%OPENSSL_DIR%\x86 WITH_SSL=dll WITH_ZLIB=dll ENABLE_WINSSL=no VC=%MsVCVersionNum% DEBUG=no MAKE="NMAKE /e" ZLIB_LFLAGS=/libpath:%ROOT_DIR%%ZLIB_DIR%\Release ZLIB_CFLAGS="/DHAVE_ZLIB_H /DHAVE_ZLIB /DHAVE_LIBZ /I%ROOT_DIR%%ZLIB_DIR%" ZLIB_LIBS=%ZLIB_IMPLIB%.lib SSL_LIBS="%SSLlib_space%" BASE_NAME=%LIBCURL_NAME% BASE_NAME_DEBUG=%LIBCURL_NAME%d7

:done